language: node_js
node_js:
  - "9"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $h # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
